-- Deprecated: definitions moved to apartment_profiles_and_settlements.sql
-- (get_apartment_profiles, settlements table/policies, get_apartment_settlements).
-- Keep this file so old docs/links still resolve; run the new script instead.
